"""
離線產生「自動關鍵詞連結圖」資料，注入 article_db/index.html。

背景：article-db 的手動連結圖只認文章內文裡的 [[標題]] wikilink，
100 多篇文章要逐篇手動互相連結不切實際。這支腳本改為：
抓全部文章 -> 用 jieba 斷詞 -> 排除虛詞(stopwords_zh.txt)與 corpus 通用詞
-> 取每篇文章的高頻詞 -> 兩篇文章共同高頻詞數達門檻就自動連一條邊
-> 把結果寫進 index.html 的 KEYWORD_GRAPH_DATA 區塊（前端會與手動
   wikilink 連結合併顯示，見 index.html 的 buildGraphData()）。

用法：
  python article_db/scripts/build_keyword_graph.py
  python article_db/scripts/build_keyword_graph.py --api-base http://localhost:8000
  python article_db/scripts/build_keyword_graph.py --top-n 12 --min-shared 2
  python article_db/scripts/build_keyword_graph.py --dry-run

跑完後照常在這個 repo 做 git commit，並記得跑
scripts/sync-article-db.ps1 把 index.html 推到 article-db-api（部署來源）。
"""
import argparse
import datetime
import io
import json
import re
import sys
import urllib.request
from collections import Counter
from pathlib import Path

# Windows 主控台常用 cp950/cp936 等非 UTF-8 codepage，中文輸出容易噴
# UnicodeEncodeError；強制 stdout/stderr 走 UTF-8（無法編碼的字元用替代符號代替）。
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

try:
    import jieba
except ImportError:
    print("缺少 jieba，請先執行：python -m pip install jieba", file=sys.stderr)
    sys.exit(1)

HERE = Path(__file__).parent
ROOT = HERE.parent
STOPWORDS_PATH = HERE / "stopwords_zh.txt"
USERDICT_PATH = HERE / "userdict_zh.txt"
INDEX_HTML_PATH = ROOT / "index.html"

MARK_START = "/* KEYWORD_GRAPH_DATA_START — auto-generated by scripts/build_keyword_graph.py, do not edit by hand */"
MARK_END = "/* KEYWORD_GRAPH_DATA_END */"
ANCHOR = "/* ── 全庫連結圖（force-directed graph，仿 Obsidian graph view） ── */"

DEFAULT_API_BASE = "https://articlebase.up.railway.app"
RAW_CANDIDATES = 30  # 每篇文章先取這麼多候選詞，再套 corpus 通用詞過濾

MD_STRIP_RE = re.compile(r"```.*?```|`[^`]*`|!\[[^\]]*\]\([^)]*\)|\[[^\]]*\]\([^)]*\)|https?://\S+|[#*_>|~]", re.S)
CJK_TOKEN_RE = re.compile(r"^[一-鿿]{2,}$")
ACRONYM_TOKEN_RE = re.compile(r"^[A-Z]{2,6}$")


def fetch_all_articles(api_base: str) -> list[dict]:
    articles = []
    offset = 0
    limit = 500
    while True:
        url = f"{api_base}/articles?limit={limit}&offset={offset}"
        with urllib.request.urlopen(url, timeout=30) as resp:
            batch = json.loads(resp.read().decode("utf-8"))
        if not batch:
            break
        articles.extend(batch)
        offset += limit
        if len(batch) < limit:
            break
    return articles


def load_stopwords() -> set[str]:
    words = set()
    if STOPWORDS_PATH.exists():
        for line in STOPWORDS_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                words.add(line)
    return words


def is_valid_token(tok: str) -> bool:
    return bool(CJK_TOKEN_RE.match(tok) or ACRONYM_TOKEN_RE.match(tok))


def tokenize(text: str, stopwords: set[str]) -> Counter:
    text = MD_STRIP_RE.sub(" ", text or "")
    counts = Counter()
    for tok in jieba.cut(text):
        tok = tok.strip()
        if not tok or tok in stopwords or not is_valid_token(tok):
            continue
        counts[tok] += 1
    return counts


def build(api_base: str, top_n: int, min_shared: int, max_doc_freq_ratio: float, title_weight: int):
    if USERDICT_PATH.exists():
        jieba.load_userdict(str(USERDICT_PATH))
    stopwords = load_stopwords()

    print(f"抓取文章列表：{api_base} ...")
    articles = fetch_all_articles(api_base)
    print(f"共 {len(articles)} 篇文章")
    if not articles:
        print("沒有抓到任何文章，中止。", file=sys.stderr)
        sys.exit(1)

    per_article_counts = {}
    for a in articles:
        aid = a["id"]
        counts = tokenize(a.get("content") or "", stopwords)
        title_counts = tokenize(a.get("title") or "", stopwords)
        for w, c in title_counts.items():
            counts[w] += c * title_weight
        per_article_counts[aid] = counts

    # corpus 內文檔頻率：某詞出現在多少篇文章的候選詞裡
    doc_freq = Counter()
    for aid, counts in per_article_counts.items():
        for w in {w for w, _ in counts.most_common(RAW_CANDIDATES)}:
            doc_freq[w] += 1

    n_articles = max(1, len(articles))
    generic = {w for w, df in doc_freq.items() if df / n_articles > max_doc_freq_ratio}

    articles_out = []
    graph_keywords = {}
    for a in articles:
        aid = a["id"]
        counts = per_article_counts[aid]
        filtered = [(w, c) for w, c in counts.most_common(RAW_CANDIDATES) if w not in generic]
        top = filtered[:top_n]
        articles_out.append({
            "id": aid,
            "keywords": [{"w": w, "c": c} for w, c in top],
        })
        graph_keywords[aid] = {w for w, _ in top}

    ids = [a["id"] for a in articles]
    edges = []
    for i in range(len(ids)):
        ki = graph_keywords[ids[i]]
        if not ki:
            continue
        for j in range(i + 1, len(ids)):
            kj = graph_keywords[ids[j]]
            if not kj:
                continue
            shared = ki & kj
            if len(shared) >= min_shared:
                edges.append({"a": ids[i], "b": ids[j], "w": len(shared), "k": sorted(shared)})

    print(f"排除 {len(generic)} 個 corpus 通用詞（出現於超過 {max_doc_freq_ratio*100:.0f}% 文章）")
    print(f"產生 {len(edges)} 條自動連結（門檻：共享 >= {min_shared} 個關鍵詞）")

    return {
        "generatedAt": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "topN": top_n,
        "minShared": min_shared,
        "articles": articles_out,
        "edges": edges,
    }


def inject_into_html(result: dict):
    html = INDEX_HTML_PATH.read_text(encoding="utf-8")
    payload = json.dumps(result, ensure_ascii=False, separators=(",", ":"))
    block = f"{MARK_START}\nconst KEYWORD_GRAPH_DATA = {payload};\n{MARK_END}"

    if MARK_START in html and MARK_END in html:
        pattern = re.compile(re.escape(MARK_START) + r".*?" + re.escape(MARK_END), re.S)
        html = pattern.sub(lambda _m: block, html, count=1)
    elif ANCHOR in html:
        html = html.replace(ANCHOR, block + "\n\n" + ANCHOR, 1)
    else:
        print("找不到插入點（KEYWORD_GRAPH_DATA 標記或連結圖錨點），index.html 結構可能已變動，請確認。", file=sys.stderr)
        sys.exit(1)

    INDEX_HTML_PATH.write_text(html, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--api-base", default=DEFAULT_API_BASE, help="文章 API 位址（預設線上 articlebase）")
    parser.add_argument("--top-n", type=int, default=12, help="每篇文章保留幾個關鍵詞用於建立連結（預設 12）")
    parser.add_argument("--min-shared", type=int, default=2, help="兩篇文章至少共享幾個關鍵詞才連線（預設 2）")
    parser.add_argument("--max-doc-freq-ratio", type=float, default=0.3, help="關鍵詞出現在超過這個比例的文章中就視為 corpus 通用詞、排除連結用途（預設 0.3）")
    parser.add_argument("--title-weight", type=int, default=3, help="標題詞彙相對內文的加權倍數（預設 3）")
    parser.add_argument("--dry-run", action="store_true", help="只印統計結果，不寫入 index.html")
    args = parser.parse_args()

    result = build(args.api_base, args.top_n, args.min_shared, args.max_doc_freq_ratio, args.title_weight)

    if args.dry_run:
        sample = json.dumps(result, ensure_ascii=False, indent=2)[:2000]
        print(sample)
        return

    inject_into_html(result)
    print(f"已寫入 {INDEX_HTML_PATH}")


if __name__ == "__main__":
    main()
